version: "3.8"

services:
  frontend:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    stdin_open: true #this 2 lines for interactive terminal
    tty: true

    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - 8000:8000
    # environment:
    #   MONGO_URL: mongourl(online db)
    #   PORT: 8000
    #   NODE_ENV: development
    env_file:
      - ./server/docker-env.env
    command: ./docker-entrypoint.sh

  # db:
  #   image: mongo:4.0-xenial
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - hallmanagement:/data/db

volumes:
  hallmanagement:
